// loaders
const LOGIN_ENABLE_LOADER = 'LOGIN_ENABLE_LOADER';
const LOGIN_DISABLE_LOADER = 'LOGIN_DISABLE_LOADER';

// theming
const SET_THEME = 'SET_THEME';

// login
const LOGIN_REQUEST = 'LOGIN_REQUEST';
const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
const LOGIN_FAILED = 'LOGIN_FAILED';
const LOG_OUT = 'LOG_OUT';

export {
  LOGIN_ENABLE_LOADER,
  LOGIN_DISABLE_LOADER,
  SET_THEME,
  LOGIN_REQUEST,
  LOGIN_RESPONSE,
  LOGIN_FAILED,
  LOG_OUT,
};
